import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./packages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "BlinkMacSystemFont",
          '"Segoe UI"',
          "Roboto",
          "Inter",
          '"Helvetica Neue"',
          "Arial",
          "sans-serif",
        ],
        mono: [
          "ui-monospace",
          '"JetBrains Mono"',
          '"SF Mono"',
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      colors: {
        background: "#f4f4f0",
        foreground: "#000000",
        card: {
          DEFAULT: "#ffffff",
          foreground: "#000000",
        },
        popover: {
          DEFAULT: "#ffffff",
          foreground: "#000000",
        },
        primary: {
          DEFAULT: "#000000",
          foreground: "#ffffff",
          navy: "#0f172a",
          light: "#1e293b",
        },
        secondary: {
          DEFAULT: "#334155",
          foreground: "#ffffff",
          steel: "#475569",
          light: "#64748b",
        },
        muted: {
          DEFAULT: "#ecece8",
          foreground: "#475569",
        },
        accent: {
          DEFAULT: "#e2e8f0",
          foreground: "#000000",
        },
        destructive: {
          DEFAULT: "#b91c1c",
          foreground: "#ffffff",
        },
        border: "#0f172a",
        input: "#0f172a",
        ring: "#000000",
        sitesync: {
          navy: "#0f172a",
          blue: "#1d4ed8",
          slate: "#334155",
          steel: "#475569",
          charcoal: "#000000",
          bg: "#f4f4f0",
          surface: "#ffffff",
          border: "#0f172a",
          sidebar: "#fbfbf9",
          green: "#15803d",
          amber: "#d97706",
          red: "#b91c1c",
        },
      },
      borderRadius: {
        none: "0px",
        sm: "0px",
        DEFAULT: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "0px",
      },
      boxShadow: {
        none: "none",
        "2xs": "1px 1px 0px 0px #0f172a",
        xs: "1px 1px 0px 0px #0f172a",
        sm: "1px 1px 0px 0px #0f172a",
        DEFAULT: "2px 2px 0px 0px #0f172a",
        md: "3px 3px 0px 0px #0f172a",
        lg: "4px 4px 0px 0px #0f172a",
        xl: "5px 5px 0px 0px #0f172a",
        "brutal-sm": "1px 1px 0px 0px #0f172a",
        brutal: "2px 2px 0px 0px #0f172a",
        "brutal-md": "3px 3px 0px 0px #0f172a",
        "brutal-lg": "4px 4px 0px 0px #0f172a",
        "brutal-black": "2px 2px 0px 0px #000000",
      },
    },
  },
  plugins: [],
};
export default config;
