export const RISK_THRESHOLDS = {
  CRITICAL_DELAY_DAYS: 4,
  WARNING_DELAY_DAYS: 1,
  STALE_UPDATE_THRESHOLD_DAYS: 7,
  LOW_CONFIDENCE_THRESHOLD: 0.70,
};

export const RISK_CATEGORIES = {
  SCHEDULE_SLIPPAGE: 'SCHEDULE_SLIPPAGE',
  STALE_UPDATE: 'STALE_UPDATE',
  DEPENDENCY_BLOCK: 'DEPENDENCY_BLOCK',
  LOW_CONFIDENCE: 'LOW_CONFIDENCE',
  DOWNSTREAM_IMPACT: 'DOWNSTREAM_IMPACT',
} as const;
