export enum UserRole {
  ADMIN = 'ADMIN',
  PLANNER = 'PLANNER',
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  VIEWER = 'VIEWER',
}

export enum Discipline {
  CIVIL = 'CIVIL',
  PIPING = 'PIPING',
  MECHANICAL = 'MECHANICAL',
  ELECTRICAL = 'ELECTRICAL',
  INSTRUMENTATION = 'INSTRUMENTATION',
  HSE = 'HSE',
  GENERAL = 'GENERAL',
}

export enum ActivityStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
  BLOCKED = 'BLOCKED',
  EXPECTED = 'EXPECTED',
}

export enum EventStatus {
  PLANNED = 'PLANNED',
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  BLOCKED = 'BLOCKED',
  EXPECTED = 'EXPECTED',
  UNKNOWN = 'UNKNOWN',
}

export enum DependencyType {
  FS = 'FS', // Finish to Start
  SS = 'SS', // Start to Start
  FF = 'FF', // Finish to Finish
  SF = 'SF', // Start to Finish
}

export enum ReportType {
  TEXT = 'TEXT',
  CSV = 'CSV',
  XLSX = 'XLSX',
  PDF = 'PDF',
  VOICE = 'VOICE',
}

export enum ProcessingStatus {
  UPLOADED = 'UPLOADED',
  PROCESSING = 'PROCESSING',
  PROCESSED = 'PROCESSED',
  FAILED = 'FAILED',
}

export enum MatchDecision {
  AUTO_LINKED = 'AUTO_LINKED',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  UNMATCHED = 'UNMATCHED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  REASSIGNED = 'REASSIGNED',
  SUPERSEDED = 'SUPERSEDED',
  HUMAN_ACCEPTED = 'HUMAN_ACCEPTED',
  HUMAN_REJECTED = 'HUMAN_REJECTED',
  HUMAN_REASSIGNED = 'HUMAN_REASSIGNED',
}

export type ReviewSortOption =
  | 'PRIORITY_DESC'
  | 'CONFIDENCE_ASC'
  | 'AMBIGUITY_DESC'
  | 'DATE_DESC'
  | 'DATE_ASC'
  | 'DOWNSTREAM_IMPACT_DESC';

export enum ReviewDecisionType {
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  SELECTED_ALTERNATIVE = 'SELECTED_ALTERNATIVE',
  MARKED_UNMATCHED = 'MARKED_UNMATCHED',
}

export enum MatchStatus {
  MATCHED = 'MATCHED',
  REVIEW_REQUIRED = 'REVIEW_REQUIRED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  REASSIGNED = 'REASSIGNED',
  UNMATCHED = 'UNMATCHED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum ReviewAction {
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT',
  REASSIGN = 'REASSIGN',
  MARK_UNMATCHED = 'MARK_UNMATCHED',
}

export enum ActorType {
  USER = 'USER',
  SYSTEM = 'SYSTEM',
  AI = 'AI',
}

export enum AuditEventType {
  MATCH_ACCEPTED = 'MATCH_ACCEPTED',
  MATCH_REJECTED = 'MATCH_REJECTED',
  MATCH_REASSIGNED = 'MATCH_REASSIGNED',
  MATCH_MARKED_UNMATCHED = 'MATCH_MARKED_UNMATCHED',
  PROGRESS_CREATED = 'PROGRESS_CREATED',
  PROGRESS_UPDATED = 'PROGRESS_UPDATED',
  PROGRESS_CORRECTED = 'PROGRESS_CORRECTED',
  ACTIVITY_STATUS_CHANGED = 'ACTIVITY_STATUS_CHANGED',
  SCHEDULE_SYNCHRONIZED = 'SCHEDULE_SYNCHRONIZED',
  REVIEW_DECISION_CREATED = 'REVIEW_DECISION_CREATED',
}

export enum EvidenceType {
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  CSV = 'CSV',
  TEXT = 'TEXT',
  VOICE = 'VOICE',
  IMAGE = 'IMAGE',
  SYSTEM = 'SYSTEM',
  PDF_PAGE = 'PDF_PAGE',
  EXCEL_CELL = 'EXCEL_CELL',
  TEXT_PARAGRAPH = 'TEXT_PARAGRAPH',
  VOICE_TRANSCRIPT = 'VOICE_TRANSCRIPT',
}

export enum RiskLevel {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum RiskType {
  SCHEDULE_DELAY = 'SCHEDULE_DELAY',
  STALE_UPDATE = 'STALE_UPDATE',
  DEPENDENCY_BLOCK = 'DEPENDENCY_BLOCK',
  LOW_CONFIDENCE_MATCH = 'LOW_CONFIDENCE_MATCH',
  MISSING_UPDATE = 'MISSING_UPDATE',
  PROGRESS_LAG = 'PROGRESS_LAG',
}

export enum RiskSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum RiskStatus {
  OPEN = 'OPEN',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  RESOLVED = 'RESOLVED',
  MITIGATED = 'MITIGATED',
}

export enum ProjectStatus {
  ON_TRACK = 'ON_TRACK',
  AT_RISK = 'AT_RISK',
  DELAYED = 'DELAYED',
  CRITICAL = 'CRITICAL',
}

export enum ScheduleHealthStatus {
  ON_TRACK = 'ON_TRACK',
  AT_RISK = 'AT_RISK',
  DELAYED = 'DELAYED',
  COMPLETED = 'COMPLETED',
  NOT_STARTED = 'NOT_STARTED',
}

export enum GanttZoomLevel {
  DAY = 'DAY',
  WEEK = 'WEEK',
  MONTH = 'MONTH',
  QUARTER = 'QUARTER',
}

export enum DelayCause {
  MATERIAL = 'MATERIAL',
  LABOR = 'LABOR',
  EQUIPMENT = 'EQUIPMENT',
  WEATHER = 'WEATHER',
  DESIGN = 'DESIGN',
  APPROVAL = 'APPROVAL',
  CONTRACTOR = 'CONTRACTOR',
  SITE_ACCESS = 'SITE_ACCESS',
  SAFETY = 'SAFETY',
  QUALITY_REWORK = 'QUALITY_REWORK',
  LOGISTICS = 'LOGISTICS',
  PLANNING = 'PLANNING',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN',
}

export enum SampleQuality {
  STRONGER_HISTORICAL_BASE = 'STRONGER_HISTORICAL_BASE', // >= 20 samples
  LIMITED = 'LIMITED', // 5-19 samples
  LOW_SAMPLE = 'LOW_SAMPLE', // < 5 samples
  INSUFFICIENT_HISTORY = 'INSUFFICIENT_HISTORY',
}

export enum ProjectClosureStatus {
  ACTIVE = 'ACTIVE',
  CLOSING = 'CLOSING',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}


